# ButlerIA Analysis and Model Training

### *1. Environment Setup*

In [11]:
import os
import numpy as np
import pandas as pd
import csv

import matplotlib.pyplot as plt

### *2. Data Discovering and Loading*

In [12]:
data_path = '../data/data_for_preprocessing.csv'

print("=====================")
print("Loading the dataset from the local machine")
print("=====================\n")

try:
    df = pd.read_csv(data_path)
    print("✅ Sucessfully Loaded!!")
except Exception as e:
    print(f"An error occurred on opening the dataset: {e}")

print("\nDataset Head:")
df.head()

=====================
Loading the dataset from the local machine
=====================

✅ Sucessfully Loaded!!

Dataset Head:

   Unnamed: 0                                               Text Author
0           0  This study investigates the chemical compositi...     AI
1           1  This study explores the cultural history of oi...     AI
2           2   Isolation of human peripheral blood mononucle...  Human
3           3   Dynamic Bayesian Networks (DBNs) are probabil...  Human
4           4   Within volleyball, performance analysis is em...  Human

### *3. Data Quality Audit*

#### Pandas functions used in the cell below:

_df.shape[0]_ = number of rows

_df.shape[1]_ = number of columns

_df.columns_ = returns an object columns

_list(df.columns)_ = transform into a list of col_names

_df.dtypes_ = returns an object for dataframe datatypes

_df.isnull().sum().sum()_ = returns number of missing values in dataframe

_df.duplicated()_ = returns a mask for duplicated rows

_df[df.duplicated()]_ = returns dataframe filtered with the mask condition

In [ ]:
print("=====================")
print("Data Quality Audit")
print("=====================\n")

# dimension
print("\n1. DATASET DIMENSIONS:")
print(f"    Rows: {df.shape[0]}")
print(f"    Columns: {df.shape[1]}\n")

# columns names
print("\n2. COLUMNS NAMES:")

col_names = list(df.columns)

for index, col in enumerate(col_names):
    print(f"    {index}. {col}")

# data types of columns
print("\n3. COLUMN DATA TYPES:")
datatypes = df.dtypes
print(f"{datatypes}")

# missing values
print(f"\n4. MISSING VALUES: {df.isna().sum().sum()}")


# duplicate rows
duplicates_mask = df.duplicated()
print(f"\n5. DUPLICATE ROWS: {len(df[duplicates_mask])}")

# dataframe head
print("\n6. FIRST 5 ROWS:")
df.head()

==================
Data Quality Audit
==================


1. DATASET DIMENSIONS:
    Rows: 6069
    Columns: 3


2. COLUMNS NAMES:
    0. Unnamed: 0
    1. Text
    2. Author

3. COLUMN DATA TYPES:
Unnamed: 0     int64
Text          object
Author        object
dtype: object

4. MISSING VALUES: 0

5. DUPLICATE ROWS: 0

6. FIRST 5 ROWS:

   Unnamed: 0                                               Text Author
0           0  This study investigates the chemical compositi...     AI
1           1  This study explores the cultural history of oi...     AI
2           2   Isolation of human peripheral blood mononucle...  Human
3           3   Dynamic Bayesian Networks (DBNs) are probabil...  Human
4           4   Within volleyball, performance analysis is em...  Human